# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0C0000)
$foreground = rgb(E4E4D4)
$color0 = rgb(0C0000)
$color1 = rgb(3F4B3D)
$color2 = rgb(B2443A)
$color3 = rgb(38735F)
$color4 = rgb(3D755F)
$color5 = rgb(818563)
$color6 = rgb(868663)
$color7 = rgb(D0D1B9)
$color8 = rgb(929282)
$color9 = rgb(546451)
$color10 = rgb(ED5B4D)
$color11 = rgb(4B9A7F)
$color12 = rgb(529C7F)
$color13 = rgb(ACB184)
$color14 = rgb(B3B384)
$color15 = rgb(D0D1B9)
