# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(27242E)
$foreground = rgb(EAC7AC)
$color0 = rgb(27242E)
$color1 = rgb(483A41)
$color2 = rgb(874742)
$color3 = rgb(486764)
$color4 = rgb(A07A62)
$color5 = rgb(D57D65)
$color6 = rgb(B5A3A3)
$color7 = rgb(EAC7AC)
$color8 = rgb(3D3A44)
$color9 = rgb(483A41)
$color10 = rgb(874742)
$color11 = rgb(486764)
$color12 = rgb(A07A62)
$color13 = rgb(D57D65)
$color14 = rgb(B5A3A3)
$color15 = rgb(EAC7AC)
