# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(121010)
$foreground = rgb(F2DBA0)
$color0 = rgb(121010)
$color1 = rgb(391B16)
$color2 = rgb(542519)
$color3 = rgb(762D1E)
$color4 = rgb(73692F)
$color5 = rgb(DE4127)
$color6 = rgb(E2985B)
$color7 = rgb(F2DBA0)
$color8 = rgb(272525)
$color9 = rgb(391B16)
$color10 = rgb(542519)
$color11 = rgb(762D1E)
$color12 = rgb(73692F)
$color13 = rgb(DE4127)
$color14 = rgb(E2985B)
$color15 = rgb(F2DBA0)
